---
- name: create user on all menaged nodes
  hosts: appserver
  tasks:
    - name: creat a user
      user:
        name: namratha
        password: yesh    
        uid: 1357
        shell: /bin/bash
        comment: "a normal user"
        home: /etc/namratha
         
...
