---
- name: Implementing host scope variables
  hosts: 172.31.20.220
  tasks:
    - name: create 
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
        uid: "{{d}}"
        shell: "{{e}}"
        comment: "{{f}}"
...          

